spring.application.name=tp8-monitoring
server.port=8080

management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true

management.prometheus.metrics.export.enabled=true

management.info.env.enabled=true
info.app.name=TP8 Spring Monitoring
info.app.version=1.0.0
info.app.description=Supervision, Logging et Monitoring avec Actuator + Prometheus + Grafana
info.app.author=ENS
info.app.endpoints.api=/api/run, /api/heavy, /api/fail, /api/status
info.app.endpoints.monitoring=/actuator, /actuator/health, /actuator/prometheus

logging.level.root=INFO
logging.level.ma.ens.tp8monitoring=DEBUG
logging.file.name=logs/tp8-monitoring.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{40} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{40} - %msg%n
